LendingApp_Challenge/force-app/main/default/objects/Loan__c/fields/LoanId__c.field-meta.xml
<CustomField>
    <fullName>LoanId__c</fullName>
    <externalId>true</externalId>
    <label>LoanId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LendingApp_Challenge/force-app/main/default/classes/LendingSystemIntegrationHelper.cls
/*****************************************************************************************************
*  LendingSystemIntegrationHelper 
* @Description: Helper class to prepare request body and process response from lending system
*				and other helper methods used to make callouts
* @Author: Vedananda Sagar
* @Created Date: 29-03-2024
* @Version History:
* -----------------------------------------------------------------------
* Version 1.1 - 
**************************************************************************/
public class LendingSystemIntegrationHelper {
    
    public static String prepareRequestToProcessLoanRecord(Loan__c loan, String accNumber, String operation) {
        
        LendingSystemIntegrationWrapper reqWrapper = new LendingSystemIntegrationWrapper();
        reqWrapper.operation = operation;//indicator for insert operation
        if(operation == 'D') {
            reqWrapper.loanId = loan.LoanId__c;      
        }else {
            if(operation == 'U') {
                reqWrapper.loanId = loan.LoanId__c;    
            }
            reqWrapper.amount = loan.Amount__c;
            reqWrapper.accountNumber = accNumber; 
        }
        
        return JSON.serialize(reqWrapper);    
    }
    
}